CREATE TABLE IF NOT EXISTS critics (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingested_at timestamp DEFAULT CURRENT_TIMESTAMP,
    display_name varchar(50),
    sort_name varchar(50),
    status varchar(50),
    bio character varying,
    seo_name varchar(50),
    multimedia jsonb
)