CREATE TABLE IF NOT EXISTS critics (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingested_at timestamp DEFAULT CURRENT_TIMESTAMP,
    display_title varchar(50),
    mpaa_rating varchar(50),
    critics_pick boolean,
    byline varchar(50),
    headline varchar(50),
    summary_short character varying,
    publication_date date,
    opening_date date,
    date_updated date,
    link character varying,
    multimedia jsonb
)